# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'PubmaticOpenwrapSdk' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PubMaticOpenWrapSDK
  pod 'OpenWrapSDK', '>=3.4.0'

end
